site_name: Daipe AI Platform
site_url: https://docs.daipe.ai
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home:
      Daipe AI Platform Documentation: index.md
      Release notes: release-notes.md
  - Getting started:
      Process Overview: getting-started/index.md
      Azure environment: getting-started/azure-setup.md
      Data Lake resources: getting-started/datalake-resources-setup.md
      Data Pipelines project: getting-started/data-pipelines-project-setup.md
      Machine Learning project: getting-started/ml-project-setup.md
      Self-hosted agents (optional): getting-started/devops-agents-setup.md
  - Developing Data Pipelines:
      Overview: data-pipelines-workflow/index.md
      Daipe demo project: data-pipelines-workflow/daipe-demo-project.md
      Create daipe project: data-pipelines-workflow/create-daipe-project.md
      Working with git: data-pipelines-workflow/working-with-git.md
      Development workflow: data-pipelines-workflow/development-workflow.md
      Detailed coding workflow: data-pipelines-workflow/coding-workflow.md
      Data pipelines workflow: data-pipelines-workflow/coding-basics.md
      Advanced features: data-pipelines-workflow/managing-datalake.md
      Databricks Connect setup: data-pipelines-workflow/databricks-connect.md
      Overcoming security limitations: data-pipelines-workflow/overcoming-security-limitations.md
      Technical documentation: data-pipelines-workflow/technical-docs.md
      Local environment setup: data-pipelines-workflow/local-env-setup.md
  - Developing ML models:
    - Workflow overview: ml-workflow/index.md
    - MLOps pipelines: ml-workflow/pipelines.md
  - Settle DQ: 
    - Overview: settle-dq/index.md
    - Getting started:
        Overview: settle-dq/getting-started/index.md
        Azure Setup: settle-dq/getting-started/azure-setup.md
        Create Configuration Notebook: settle-dq/getting-started/configuration-notebook.md
    - Developing Expectations:
        Workflow Overview: settle-dq/developing-expectations/index.md
        Developing and Storing DQ Expectations: settle-dq/developing-expectations/develop-store.md
        Validating Your Data: settle-dq/developing-expectations/validation.md
        Viewing Validation Results: settle-dq/developing-expectations/view-validation-results.md
        Editing Expectations: settle-dq/developing-expectations/edit.md

