site_name: Daipe AI Platform
repo_url: https://github.com/daipe-ai/platform-docs/
site_url: https://daipe-ai.github.io/platform-docs/
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Getting started:
      Process Overview: getting-started/index.md
      Azure environment: getting-started/azure-setup.md
      Data Lake resources: getting-started/datalake-resources-setup.md
      Data Pipelines project: getting-started/data-pipelines-project-setup.md
      Machine Learning project: getting-started/ml-project-setup.md
      Self-hosted agents (optional): getting-started/devops-agents-setup.md
  - Developing Data Pipelines:
      Workflow overview: data-pipelines-workflow/index.md
      Detailed coding workflow: data-pipelines-workflow/coding-workflow.md
      Function-based notebooks: data-pipelines-workflow/coding-basics.md
      Managing datalake: data-pipelines-workflow/managing-datalake.md
      Local development env: data-pipelines-workflow/local-env-setup.md
      Databricks Connect setup: data-pipelines-workflow/databricks-connect.md
  - Developing ML models:
    - Workflow overview: ml-workflow/index.md
