site_name: AI Platform
repo_url: https://github.com/DataSentics/ai-platform-docs/
site_url: https://datasentics.github.io/ai-platform-docs/
theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - fancyboxmd

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

# Page tree
nav:
  - Home: index.md
  - Getting started:
    - getting-started/index.md
    - getting-started/azure-setup.md
    - getting-started/resources-setup.md
    - getting-started/first-datalake-project.md
    - getting-started/first-ml-project.md
  - Developers workflow:
    - developers-workflow/datalake-project-workflow.md
    - developers-workflow/setup-local-project.md
    - developers-workflow/feature-branch.md