site_name: AI Suite
repo_url: https://github.com/DataSentics/ai-platform-docs/
site_url: https://datasentics.github.io/ai-platform-docs/
theme:
  name: material
  features:
    - navigation.tabs

markdown_extensions:
  - fancyboxmd

extra_css:
  - stylesheets/extra.css
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js
  - https://cdn.jsdelivr.net/gh/fancyapps/fancybox@3.5.7/dist/jquery.fancybox.min.js

# Page tree
nav:
  - Home: index.md
  - Getting started:
      Getting started: getting-started/index.md
      Azure environment: getting-started/azure-setup.md
      Data Lake resources: getting-started/datalake-resources-setup.md
      Data Pipelines project: getting-started/data-pipelines-project-setup.md
      Machine Learning project: getting-started/ml-project-setup.md
  - Developing Data Pipelines:
      Workflow overview: data-pipelines-workflow/index.md
      Feature branch: data-pipelines-workflow/feature-branch.md
      Local project setup: data-pipelines-workflow/setup-local-project.md
  - Developing ML models:
    - Workflow overview: ml-workflow/index.md
