site_name: AI Platform
repo_url: https://github.com/DataSentics/ai-platform-docs/
site_url: https://datasentics.github.io/ai-platform-docs/
theme:
  name: material
  features:
    - navigation.tabs

# Page tree
nav:
  - Home: home/index.md
  - Getting started:
    - getting-started/index.md
    - getting-started/azure-setup.md
    - getting-started/resources-setup.md
    - getting-started/first-datalake-project.md
    - getting-started/first-ml-project.md
