site_name: AI Suite
repo_url: https://github.com/DataSentics/ai-platform-docs/
site_url: https://datasentics.github.io/ai-platform-docs/
theme:
  name: material
  features:
    - navigation.tabs
    - toc.integrate

markdown_extensions:
  - attr_list

extra_css:
  - stylesheets/extra.css

# Page tree
nav:
  - Home: index.md
  - Getting started:
      Process Overview: getting-started/index.md
      Azure environment: getting-started/azure-setup.md
      Data Lake resources: getting-started/datalake-resources-setup.md
      Data Pipelines project: getting-started/data-pipelines-project-setup.md
      Machine Learning project: getting-started/ml-project-setup.md
      Self-hosted agents (optional): getting-started/devops-agents-setup.md
  - Developing Data Pipelines:
      Workflow overview: data-pipelines-workflow/index.md
      Create new feature: data-pipelines-workflow/feature-branch.md
      (Advanced) Local project setup: data-pipelines-workflow/setup-local-project.md
  - Developing ML models:
    - Workflow overview: ml-workflow/index.md
